# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Tue Feb 27 11:18:29 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 660)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBoxTests = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBoxTests.sizePolicy().hasHeightForWidth())
        self.groupBoxTests.setSizePolicy(sizePolicy)
        self.groupBoxTests.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBoxTests.setBaseSize(QtCore.QSize(0, 0))
        self.groupBoxTests.setObjectName("groupBoxTests")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxTests)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetTest = QtGui.QTabWidget(self.groupBoxTests)
        self.tabWidgetTest.setObjectName("tabWidgetTest")
        self.verticalLayout.addWidget(self.tabWidgetTest)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startSetButton = QtGui.QPushButton(self.groupBoxTests)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icons/PlayMultiple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startSetButton.setIcon(icon)
        self.startSetButton.setObjectName("startSetButton")
        self.horizontalLayout.addWidget(self.startSetButton)
        self.startTestButton = QtGui.QPushButton(self.groupBoxTests)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/icons/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startTestButton.setIcon(icon1)
        self.startTestButton.setObjectName("startTestButton")
        self.horizontalLayout.addWidget(self.startTestButton)
        self.abortButton = QtGui.QPushButton(self.groupBoxTests)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/icons/Cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abortButton.setIcon(icon2)
        self.abortButton.setObjectName("abortButton")
        self.horizontalLayout.addWidget(self.abortButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBoxResults = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxResults.sizePolicy().hasHeightForWidth())
        self.groupBoxResults.setSizePolicy(sizePolicy)
        self.groupBoxResults.setObjectName("groupBoxResults")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxResults)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TreeViewResults = QtGui.QTreeView(self.groupBoxResults)
        self.TreeViewResults.setIconSize(QtCore.QSize(20, 20))
        self.TreeViewResults.setObjectName("TreeViewResults")
        self.verticalLayout_4.addWidget(self.TreeViewResults)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gotoLogButton = QtGui.QPushButton(self.groupBoxResults)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/icons/Script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoLogButton.setIcon(icon3)
        self.gotoLogButton.setObjectName("gotoLogButton")
        self.horizontalLayout_2.addWidget(self.gotoLogButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBoxLog = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxLog.sizePolicy().hasHeightForWidth())
        self.groupBoxLog.setSizePolicy(sizePolicy)
        self.groupBoxLog.setObjectName("groupBoxLog")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxLog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidgetLog = QtGui.QTabWidget(self.groupBoxLog)
        self.tabWidgetLog.setObjectName("tabWidgetLog")
        self.verticalLayout_2.addWidget(self.tabWidgetLog)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.closeLogsButton = QtGui.QPushButton(self.groupBoxLog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/icons/WideBrush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeLogsButton.setIcon(icon4)
        self.closeLogsButton.setObjectName("closeLogsButton")
        self.horizontalLayout_3.addWidget(self.closeLogsButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuResults = QtGui.QMenu(self.menubar)
        self.menuResults.setObjectName("menuResults")
        self.menuLogs = QtGui.QMenu(self.menubar)
        self.menuLogs.setObjectName("menuLogs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui/icons/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStartTest = QtGui.QAction(MainWindow)
        self.actionStartTest.setIcon(icon1)
        self.actionStartTest.setObjectName("actionStartTest")
        self.actionAbort = QtGui.QAction(MainWindow)
        self.actionAbort.setIcon(icon2)
        self.actionAbort.setObjectName("actionAbort")
        self.actionStartSet = QtGui.QAction(MainWindow)
        self.actionStartSet.setIcon(icon)
        self.actionStartSet.setObjectName("actionStartSet")
        self.actionTestResultsClicked = QtGui.QAction(MainWindow)
        self.actionTestResultsClicked.setObjectName("actionTestResultsClicked")
        self.actionActionCloseLogs = QtGui.QAction(MainWindow)
        self.actionActionCloseLogs.setIcon(icon4)
        self.actionActionCloseLogs.setObjectName("actionActionCloseLogs")
        self.actionActionGotoLog = QtGui.QAction(MainWindow)
        self.actionActionGotoLog.setIcon(icon3)
        self.actionActionGotoLog.setObjectName("actionActionGotoLog")
        self.menuFile.addAction(self.actionQuit)
        self.menuTest.addAction(self.actionStartSet)
        self.menuTest.addAction(self.actionStartTest)
        self.menuTest.addAction(self.actionAbort)
        self.menuResults.addAction(self.actionActionGotoLog)
        self.menuLogs.addAction(self.actionActionCloseLogs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuResults.menuAction())
        self.menubar.addAction(self.menuLogs.menuAction())
        self.toolBar.addAction(self.actionStartSet)
        self.toolBar.addAction(self.actionStartTest)
        self.toolBar.addAction(self.actionAbort)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionGotoLog)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionActionCloseLogs)

        self.retranslateUi(MainWindow)
        self.tabWidgetTest.setCurrentIndex(-1)
        self.tabWidgetLog.setCurrentIndex(-1)
        QtCore.QObject.connect(self.startSetButton, QtCore.SIGNAL("clicked()"), self.actionStartSet.trigger)
        QtCore.QObject.connect(self.startTestButton, QtCore.SIGNAL("clicked()"), self.actionStartTest.trigger)
        QtCore.QObject.connect(self.abortButton, QtCore.SIGNAL("clicked()"), self.actionAbort.trigger)
        QtCore.QObject.connect(self.TreeViewResults, QtCore.SIGNAL("doubleClicked(QModelIndex)"), self.actionTestResultsClicked.trigger)
        QtCore.QObject.connect(self.closeLogsButton, QtCore.SIGNAL("clicked()"), self.actionActionCloseLogs.trigger)
        QtCore.QObject.connect(self.gotoLogButton, QtCore.SIGNAL("clicked()"), self.actionActionGotoLog.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTests.setTitle(QtGui.QApplication.translate("MainWindow", "Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.startSetButton.setText(QtGui.QApplication.translate("MainWindow", "Start Test Set", None, QtGui.QApplication.UnicodeUTF8))
        self.startTestButton.setText(QtGui.QApplication.translate("MainWindow", "Start Test", None, QtGui.QApplication.UnicodeUTF8))
        self.abortButton.setText(QtGui.QApplication.translate("MainWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxResults.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoLogButton.setText(QtGui.QApplication.translate("MainWindow", "Goto Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxLog.setTitle(QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.closeLogsButton.setText(QtGui.QApplication.translate("MainWindow", "Close Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest.setTitle(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.menuResults.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLogs.setTitle(QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartTest.setText(QtGui.QApplication.translate("MainWindow", "Start Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartTest.setToolTip(QtGui.QApplication.translate("MainWindow", "Start Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartTest.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbort.setText(QtGui.QApplication.translate("MainWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartSet.setText(QtGui.QApplication.translate("MainWindow", "Start Test Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartSet.setToolTip(QtGui.QApplication.translate("MainWindow", "Start Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTestResultsClicked.setText(QtGui.QApplication.translate("MainWindow", "TestResultsClicked", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionCloseLogs.setText(QtGui.QApplication.translate("MainWindow", "Close Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActionGotoLog.setText(QtGui.QApplication.translate("MainWindow", "Goto Log", None, QtGui.QApplication.UnicodeUTF8))

